### ISSUE TITLE
Readme question

### ISSUE THREAD

**Issue by SheepFromHeaven** [virtualidentityag/key-buddy#7]
Why do I need global versions of vue and vue-cli?
```
npm install -g vue
npm install -g @vue/cli
```

Shouldn't it work without

**Comment by stefanieneubert** [comment]
Good point. I will update it.

**Comment by dweiger** [comment]
I think you need the cli globally to use it for creating a new project. this is an already created project so we won't need it in the readme

**Comment by stefanieneubert** [comment]
#10
